name: Unit tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  run_unit_tests:
runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install pycodestyle
          find . -name "*.py" -not -path "./.venv/*" -print0 | xargs -0 -n 1 pycodestyle
          
  run_func_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash el {0}
    steps:
      - uses: action/checkout@v2
      - run: |
          cd test/function/
          bash test_print_fires.sh

      - run: |
          cd src/
          bash run.sh

  run_style_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install pycodestyle
          find . -name "*.py" -not -path "./.venv/*" -print0 | xargs -0 -n 1 pycodestyle