name: Unit tests

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          cd test/unit
          python -m unittest test_my_utils

  run_func_tests:
    runs-on: macOS-ventura-13.4.1
    defaults:
      run:
        shell: bash el {0}
    steps:
      - uses: action/checkout@v2
      - uses: 
      - run: |
          cd test/function/
          bash test_print_fires.sh

          cd src/
          bash run.sh

  run_style_tests:
    runs-on: macOS-ventura-13.4.1
    defaults:
      run:
        shell: pip install pycodestyle
    steps:
      - uses: action/checkout@v2
      - uses: actions/setup-python@v2
        with:

      - run: |
      find . -name "*.py" -not -path "./.venv/*" -print0 | xargs -0 -n 1 pycodestyle
